# Generated by Django 3.1.7 on 2021-05-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('facing', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_rate', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month')], max_length=30)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size_scale', models.CharField(choices=[('Inches', 'Inches'), ('Feet', 'Feet'), ('Meter', 'Meter')], max_length=30)),
                ('advertisement_type', models.CharField(choices=[('Bill Board', 'Bill Board'), ('Vehicle', 'Vehicle')], max_length=30)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.advertisermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('duration', models.CharField(max_length=30)),
                ('price_rate', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month')], max_length=30)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('advertiser_paid_approval', models.BooleanField(default=False)),
                ('customer_paid_approval', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('advertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_control.advertisemodel')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_control.ordermodel')),
            ],
        ),
    ]
