# Generated by Django 3.1.7 on 2021-04-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
        ('ad_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('duration', models.IntegerField(max_length=10)),
                ('price_rate', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month')], max_length=30)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advertisemodel',
            name='advertisement_type',
            field=models.CharField(choices=[('Bill Board', 'Bill Board'), ('Vehicle', 'Vehicle')], max_length=30),
        ),
        migrations.CreateModel(
            name='OrderPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_control.ordermodel')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='advertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_control.advertisemodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_control.customermodel'),
        ),
    ]
