# Generated by Django 3.1.7 on 2021-04-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_control', '0002_auto_20210403_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_active',
            new_name='is_complete',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
