# Generated by Django 3.1.7 on 2021-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_control', '0003_auto_20210404_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
