# Generated by Django 3.1.7 on 2021-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_control', '0004_ordermodel_additional_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
