# Generated by Django 3.1.7 on 2021-04-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_control', '0005_ordermodel_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaymentmodel',
            name='is_paid',
        ),
    ]
