# Generated by Django 3.1.7 on 2021-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_control', '0006_remove_orderpaymentmodel_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_paid',
            new_name='advertiser_paid_approval',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer_paid_approval',
            field=models.BooleanField(default=False),
        ),
    ]
